# Generated by Django 3.2.12 on 2022-02-07 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id_questions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Answer', to='test_drf.question', verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=200, verbose_name='Пользователь')),
                ('id_answer', models.ForeignKey(default='-', on_delete=django.db.models.fields.CharField, related_name='UserAnswerAnswers', to='test_drf.answer', verbose_name='Ответ')),
                ('id_contest', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserAnswerContests', to='test_drf.contest', verbose_name='Конкурс')),
                ('id_questions', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserAnswerQuestions', to='test_drf.question', verbose_name='Вопрос')),
            ],
        ),
    ]
