# Generated by Django 3.2.12 on 2022-02-07 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_drf', '0002_auto_20220207_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='id_answer',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.fields.CharField, related_name='UserAnswerAnswers', to='test_drf.answer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id_contest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='UserAnswerContests', to='test_drf.contest', verbose_name='Конкурс'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='id_questions',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='UserAnswerQuestions', to='test_drf.question', verbose_name='Вопрос'),
        ),
    ]
